jobs:
- pysparkJob:
    args:
    - --job=load_loans
    - --job-args=gcs_input_path=gs://hamza-test-dataproc-workflowtemplates/ibrd-statement-of-loans-historical-data.csv
    - --job-args=gcs_output_path=gs://hamza-test-dataproc-workflowtemplates/ibrd-summary-large-python
    mainPythonFileUri: gs://hamza-test2-dataproc-workflowtemplates/dist/main.py
    pythonFileUris:
    - gs://hamza-test2-dataproc-workflowtemplates/dist/jobs.zip
  stepId: ibrd-large-pyspark
placement:
  managedCluster:
    clusterName: three-node-cluster
    config:
      gceClusterConfig:
        zoneUri: europe-west1-c
      masterConfig:
        diskConfig:
          bootDiskSizeGb: 500
        machineTypeUri: n1-standard-4
      softwareConfig:
        imageVersion: 1.3-deb9
      workerConfig:
        diskConfig:
          bootDiskSizeGb: 500
        machineTypeUri: n1-standard-4
        numInstances: 2
